### PR TITLE
Update surfing.md

### PR DESCRIPTION
**Pull request by tarynosaurus**

### CODE REVIEW

**Comment by mprat** [comment]
If the formatting is confusing and you need help just comment on here and
we can help!

**Comment by tarynosaurus** [comment]
Hello! I edited the boathouse page on github to include surfboard rentals,
but I'm not sure how to commit those changes to the website. Thanks!

-Taryn

**Comment by mprat** [comment]
I don't see any changes to this pull request - can you push your changes? I am happy to review and merge (which will push them live). Where and how did you make the edits?

**Comment by tarynosaurus** [comment]
I went to the boathouse page on github, and then next to the edit button
(which was greyed out) I clicked "Open in github.dev" which was the only
clickable option.

I know a bit of coding, but not very familiar with using github!

-Taryn

**Comment by mprat** [comment]
I can't figure out where you made the edits, sorry! I can make any changes you want (and I'll attach it to this pull request so we can see the batched changes). A few clarifications:

* Do we in fact have surfboards to rent? There isn't any gear in the gear database listed as surfboards. I see windsurfing, but as I recall the surf stuff was different! Any clarification on that would be helpful.
* If we DO rent surfboards, what is the daily rental price and the deposit price? We need to get them added not just to the website but to the gear database as well.

I'm going to start an email chain to get this figured out, so we can swap to that.

**Review by mprat — APPROVED** [review]

**Pull request merged**
