### PR TITLE
fix some deposits / gear prices

### PR DESCRIPTION
**Pull request by mprat**
Update some of the obvious deposit / rental incorrectnesses with the fees to make them consistent with the DB. More to come.

### CODE REVIEW

**Review by fpagnoux — APPROVED** [review]
Looks good to me

**Comment by luthern** [comment]
I think the microspikes are intended to be 50, not 80. Did you get these values by averaging? In general, I think the averages should exclude the $100 entry that was the default value

**Comment by mprat** [comment]
Yea, I got these by averaging across all non-retired, non-broken, gear in
the fleet. I'll change the microspikes to back to $50 and merge.

Should all the microspikes in the DB then be changed to have a $50 deposit?

**Comment by luthern** [comment]
Can we please get a look at this from @ColeDCrawford or @mglidden? The two of them have a bit better context for the cost of gear as they bought a lot of it. It's possible that the general trend of increased deposits in this PR for items with deposits less than $100 is not desirable, as those $100 entries were likely set to the default value for deposit in the DB.

**Comment by luthern** [comment]
In particular I think the trekking poles really are supposed to be $40 each, and the ATC + biner, harness, and helmet values might be similarly inflated. The folks I pinged above should be able to advise further.

**Comment by mprat** [comment]
I'm fine with whatever you guys want to change, whether that is in the DB or the website - just let me know which one is desirable and I'll do that one. (e.g. one reasonable outcome is to say "change all the trekking poles in the DB to have a deposit of XX" and I'll go ahead and run a query on that)

**Comment by luthern** [comment]
I think generally the deposit data in the website is the set that's closer to correct. We'd like for them to be consistent, and in an ideal world for the values to be pulled from the DB instead of handwritten into the website YAML files so that this kind of deconfliction isn't necessary in the future. 

A separate PR I would support would be an edit to the gear addition function on mitoc-gear that *required* a selection of a deposit value for all new gear, eliminated the default, and encouraged people to check with the gear managers if they were not sure what to enter in that field.

**Comment by mprat** [comment]
Yea I'm working on the DB-side that does the "pull the average deposit
value and populate this" - I'm hoping to have a prototype by EOD tomorrow.

I can easily do the fix for the new gear additions that you're asking
about; I didn't know it was a desired feature. Issue created in the gear DB
repo.

**Review by ColeDCrawford — COMMENTED** [review]
- Elixir 2 person tent cost to MITOC was $172; 4 person was $275. We can't get those prices for the foreseeable future (Cascade Designs' response to COVID supply chain issues). Retail is currently $250 / $400.
- MSR Evo Snowshoes retail for $140, $95 to MITOC, if they were ever available
- BD First Light mountaineering tents retail for $400, $250 to MITOC
- $400 seems low for the fatbike but I confess to knowing nothing about it

**Comment by fpagnoux** [comment]
I'm not sure about this idea of _averaging_ the deposit amount within a category to determine what we display on the website. 

This feels unnecessarily complex, and potentially confusing. Let's say I'm planning to rent a sleeping bag, and the website tells me the deposit is $80, because some sleeping bags have a $100 deposit, and some other have a $60 deposit. The deposit check I'm writing at home is going to be either too high or too low for my rental. 

I think showing deposit amounts by gear type on the website implies that this amount is the same for all (or maybe 95%) of items within this category. And I think that's realistic: the vast majority of gear items in the office are standardized and don't required an item-level deposit amount. 

So the approach I'd lean towards is:
- Add a new "deposit" field for gear types in the database. 
  - For each gear type, populate this field with what's currently on the website (or whatever amount the gear/desk managers think is better)
- Expose the list of gear types with the deposits and rentals prices as a public API route. Use this data on the website. 
- Keep the ability to override the amount for a specific item (e.g. a down sleeping bag). But this would be the exception rather than the rule.

**Comment by mprat** [comment]
>     * Elixir 2 person tent cost to MITOC was $172; 4 person was $275. We can't get those prices for the foreseeable future (Cascade Designs' response to COVID supply chain issues). Retail is currently $250 / $400.
> 
>     * MSR Evo Snowshoes retail for $140, $95 to MITOC, if they were ever available
> 
>     * BD First Light mountaineering tents retail for $400, $250 to MITOC
> 
>     * $400 seems low for the fatbike but I confess to knowing nothing about it

@ColeDCrawford does your comment imply the following actions:

* 2-person tent deposits on website should be $250? The DB currently lists all Elixir 2-person tents as having a deposit of $250, but there are other 2-person tents in the DB that are other models which is what is driving down the price listed on the website. Would you recommend simply listing $250 as the deposit on the website?
* 4-person tent deposits on website should be $400. Same for this; all 4-person Elixir tents in the DB are listed as having a $400 deposit, but there are other 4-person tents (e.g. the Shifter 4 has a deposit listed of $180 in the DB) that are driving down the average calculated here. Would you recommend just listing 4-person tent deposits at $400 on the website, knowing that the shifters are much cheaper deposit-wise?
* MSR Evo snowshoes currently in the DB are shown to have $100 deposit - are you recommending bumping it up to $140 in the DB and therefore bumping up the price on the website as well?
* I'll ask the bike chairs about the bikes.
*

**Comment by ColeDCrawford** [comment]
Yes, if we're using retail prices for deposits, then I'd just go with the Elixir retail prices for deposits for consistency even for the older tents as if those are broken / damaged it's that's what we'd need to pay to replace them. Same for the snowshoes.

**Comment by mprat** [comment]
Alright, snowshoe / tent prices in this PR and the DB updated according to cole's comment.

How do the rest of these prices look? In particular @luthern @mglidden @ColeDCrawford there are a few questions that Noah brought up that I'd like some clarity and direction on what is desired:

1. Microspikes in the database - the deposit is currently set to 50 for some, and 100 for others. What do we want to do here, both in the DB and on the website? I think based on what you said @luthern that these should ALL be changed to $50 in the DB, and the website updated accordingly. Is this correct?
2. Trekking poles: some in the DB have a deposit of $40, some are $80, and some are $100. Do we want all of them the same at $80? 
3. ATC + locking biner: some of them in the DB are $20 (Black Diamond), some are $30 (Petzl Reverso), some are $100 (Petzl Verso). What do we want to do here, both in the DB and on the website? If this particular question is for the climbing chairs, I can ask, but please let me know.

Really want to get this CR merged to update the pricing on the website in advance of winter school, so I appreciate the feedback!

**Comment by luthern** [comment]
> Alright, snowshoe / tent prices in this PR and the DB updated according to cole's comment.
> 
> How do the rest of these prices look? In particular @luthern @mglidden @ColeDCrawford there are a few questions that Noah brought up that I'd like some clarity and direction on what is desired:
> 
>     1. Microspikes in the database - the deposit is currently set to 50 for some, and 100 for others. What do we want to do here, both in the DB and on the website? I think based on what you said @luthern that these should ALL be changed to $50 in the DB, and the website updated accordingly. Is this correct?
> 
Yes, $50 sounds good to me.

>     2. Trekking poles: some in the DB have a deposit of $40, some are $80, and some are $100. Do we want all of them the same at $80?
> 
Each individual pole should be $20 on deposit, for a total of $40 per pair.

>     3. ATC + locking biner: some of them in the DB are $20 (Black Diamond), some are $30 (Petzl Reverso), some are $100 (Petzl Verso). What do we want to do here, both in the DB and on the website? If this particular question is for the climbing chairs, I can ask, but please let me know.
> 
The verso price is wild, so that seems like it's definitely a default value. I'd put all the ATC+locker at $30 across the board and update the website to that deposit.
> 
> Really want to get this CR merged to update the pricing on the website in advance of winter school, so I appreciate the feedback!

Thanks again!

**Comment by mprat** [comment]
@luthern all 3 items above changed accordingly!

Any other issues with this website update that we want to discuss? I'm working on the public deposit amount view that should make this much easier in the future.

**Comment by luthern** [comment]
Looks good to me! If there’s more to change we can do it in a different PR

**Pull request merged**
